### ISSUE TITLE
sablier sur acces carto ?

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#13]
Carte : Ce serait bien d’avoir un sablier quand on clique car l’action est relativement longue (la réaction sur Android est différente par rapport à IOS, car l’écran ne change pas - donc on a l’impression qu’il ne se passe rien -, puis la carte s’ouvre). Un effet bizarre :  si on clique sur le menu carte, et pendant qu’il ne se passe rien, sur le menu paramètres, cela ouvre l’écran paramètres, puis au bout d’un moment l’écran carte s’ouvre alors que l’on n’a rien demandé.

**Comment by vm-agoralogie** [comment]
Pas d'événement d'ouverture ou fermeture effective du navigateur envoyé par le plugin.
Si je mets un sablier, je ne peux pas savoir quand sortir de cet état.
