### ISSUE TITLE
How to add new devices ?

### ISSUE THREAD

**Issue by ChristianSimonSU** [openradiation/openradiation-mobile#137]
Hi,

I developped the device which name was OGCMS. 
I added some files and adapted them from OGKit, although there maybe upper/lower case issues. The app remains stuck during initialization (device is well detected, connected and turned on).

But the question is larger than this case. If we start to develop a new device, what are the changes to include to get "hwdev" device (for example).

Up to now I identified: 
openradiation-mobile/src/app/states/devices/ble/device-og-kit.service.ts
openradiation-mobile/src/app/states/devices/ble/device-og-kit.ts
openradiation-mobile/src/app/states/devices/ble/ble-devices.service.ts

Thanks in advance,

**Comment by TomDemulierChevret** [comment]
Have you followed the [ADD_NEW_SENSOR](https://github.com/openradiation/openradiation-mobile/blob/master/ADD_NEW_SENSOR.md) instructions ?

**Comment by ChristianSimonSU** [comment]
I did not even notice there was such instructions 🤦🏻‍♂️ 
I'll try it and keep you informed.

**Comment by ChristianSimonSU** [comment]
All right, I did something almost logical: the sensor is virtually the same as OG-KIT1, excepted it's more compact. Therefore, I duplicated every file were I found OG-KIT or named *og-kit* replacing it with og-cms. Even the tubes and conversion factors are the same.

But I wonder if there is a conflict, since both share the same name begining "og"... especially in device-og-cms-service.ts

**Comment by ChristianSimonSU** [comment]
One more question: is there a debug mode to investigate the data exchange ?
How did you define UUIDs ?

**Comment by TomDemulierChevret** [comment]
If you launch the app on your phone with `npm run run:android` then you can debug it with Chrome remote debug.
If you go to `chrome://inspect/#devices` you will see the different Android phone connected to your PC and the web/hybrid app running on them that you can debug.

The UUIDs are set by the bluetooth configuration of the sensor.
