### ISSUE TITLE
navigation carto

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#14]
Carte : Sous Android , il n’y a pas de bouton « Fermer » comme sur iOS 
![carte](https://cloud.githubusercontent.com/assets/547222/18951833/75a33c72-8647-11e6-86de-a31242716f43.png)
 : du coup cela donne vraiment l’impression d’être sorti de l’application le rendu n’est pas très agréable. Le seul moyen de revenir est le bouton « retour arrière ». Peut-on mettre la carte dans le cadre de l’application (avec titre en haut et menu en bas) ?

**Comment by vm-agoralogie** [comment]
Le plugin n'offre pas cette option.
Il faut faire "back" pour fermer.
