### ISSUE TITLE
attente infini sur initialisation

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#35]
si le device se déconnecte pendant l'initialisation, celle ci ne finit jamais.
Prévoir un time-out à 40 secondes qui renvoit sur la page d'accueil.
Ou un bouton "retour à l'accueil" 
en fait il faut surtout eviter que l'utilisateur ait a quitter l'application pour la relancer

Note : Mail Genevieve B 1/2/2017

**Comment by pmlaroche-agoralogie** [comment]
de temps en temps, il est necessaire de killer l'application.
pistes de reflexion : 
+ bouton cancel
+surveillance en permanence

**Comment by ghisd** [comment]
Dans l'écran "mesure en cours", dès le début (phase d'initialisation), afficher un bouton annuler qui permet d'annuler la mesure à tout moment et revenir à la page d'accueil

**Comment by TomDemulierChevret** [comment]
Fixed by #74
