### ISSUE TITLE
Prise en main guidée à l'accueil

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#36]
Sur les textes  : « Je ne sais pas où l’on trouve ces explications quand on achète l’application. elle n’apparaissent pas quand on ouvre l’application pour s’en servir. Pourquoi pas un bouton à l’entrée avec « quelques rappels » ou quelque chose comme cela. 
Les rappels seraient :  
"Vérifier que le blue tooth est bien allumé". 
"Il faut 20 secondes pour que l’initiation soit terminée sinon il faut relancer l’application. "
"Redémarrer l’application si vous avez arrêté le capteur. "
"Si vous voulez que vos données soient envoyées automatiquement mettez le bouton « on » sur le réglage mode expert  »."

**Comment by pmlaroche-agoralogie** [comment]
Reflechir sur l'aide "en cours de fonctionnement"

**Comment by ghisd** [comment]
ticket clos pour l'instant
