### ISSUE TITLE
GPS obligatoire pour prendre une mesure

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#48]
Ne pas rendre le GPS obligatoire, peut etre mettre un warning quand meme si les gens insistent pour prendre la mesure.
En revanche, la mesure ne sera jamais envoyée : ni en envoi automatique, ni en manuel avec le bouton envoi.
Envisager une mécanisme pour informer sur ce point : peut etre sur la page "mesure détaillée"

**Comment by TomDemulierChevret** [comment]
Fixed by #75
