### ISSUE TITLE
Revisualiser une mesure

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#49]
dans historique, pouvoir cliquer sur une ligne mesure et la visualiser avec le même niveau de détail qu'en mode saisie manuelle (mais pas de modification possible)

**Comment by ghisd** [comment]
Si la mesure n’a pas été publiée, les modifications des métadonnées (environnement, tags, photo…) sont possibles selon les mêmes conditions que dans les conditions initiales. Si c'est une saisie manuelle non encore publiée, tout est modifiable.

**Comment by TomDemulierChevret** [comment]
Fixed by #78
