### ISSUE TITLE
Passage en tache de fond sous iOS

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#50]
Le passage en tache de fond interdit la communication avec le capteur.
A la fin de l'initialisation, l'application prends note du timestamp.
Lorsque l'application redevient active, elle regarde le temps écoulé depuis l'initialisation, même si elle n'a pas reçu de communication avec le capteur pendant une longue période.
le calcul de coups/minute est donc faux.

Actions possibles : ne compter que les secondes où il y a eu un retour du capteur / réduire l'intervalle heure de début - heure de fin envoyé à l'API

**Comment by ghisd** [comment]
Corrigée en 1.0.0
