### ISSUE TITLE
Messages dynamiques venant du webmaster ou des notifications

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [openradiation/openradiation-mobile#55]
L'idée est de pouvoir faire parvenir des messages à l'ensemble des utilisateurs de l'application.

Pistes de réflexion : 
L'application au lancement interroge un service Message_Of_The_Day, si un texte est renvoyé, il sera affiché sur la page d'accueil de l'application, pour que l'actualité soit bien lue (sinon rien).

Autre option :  notification système meme si application inactive

**Comment by ghisd** [comment]
Ticket clos pour l'instant - à réfléchir
