### ISSUE TITLE
Hits number very high just after the initialization phase

### ISSUE THREAD

**Issue by ghisd** [openradiation/openradiation-mobile#59]
Sometimes when taking a measurement, just after the initialization phase, hits number is very high. After a moment the hits number / min decrease. It appears maybe we start to measure too soon

**Comment by pmlaroche-agoralogie** [comment]
i saw this a few times, but i don't think it is an issue with the time we begin to count : if the voltage is too low, there is no hit. anyway, it is easy to change the voltage range which is used.

**Comment by ghisd** [comment]
Apparently, this problem occurs only with certain sensors. I close the issue, we have to first check the sensors involved
