### ISSUE TITLE
Sensor disconnected - message

### ISSUE THREAD

**Issue by ghisd** [openradiation/openradiation-mobile#60]
When the sensor is disconnected, a esoteric message is displayed "failure ... "

**Comment by ghisd** [comment]
The message "Failure 
AA:AA:AA:AA:AA:AA non connecté" is to be replaced by 
"Information
Capteur déconnecté" in french or "Information Sensor disconnected" in english.

The information should be updated in the application (when a sensor is disconnected, after this message we always see "Capteur détecté" on the main screen and in the parameters)

**Comment by TomDemulierChevret** [comment]
Fixed with incoming V2.
