### ISSUE TITLE
GPS not accurate

### ISSUE THREAD

**Issue by ghisd** [openradiation/openradiation-mobile#62]
Sometimes, the position is wrong from a few kilometers.

This is an example of data with Android 6.0 (Honor6c) : 
latitude | longitude | accuracy | altitude | altitudeAccuracy 
**45.9902007 | -1.3701963 | 3100 | 0 |**   
45.9990568 | -1.3877018 | 6 | 63 |   
46.0319799 | -1.4062212 | 4 | 55 |   
46.0406378 | -1.4102183 | 10 | 53 |   
46.0477108 | -1.408215 | 3 | 56 |   
**46.0334874 | -1.3863353 | 2500 | 0 |**   
46.0414671 | -1.3872335 | 5 | 60 |   
46.0389214 | -1.3831669 | 4 | 69 |  

The 2 bold lines have a wrong GPS position. We can see that accuracy is very high and altitude is 0. 

We should investigate with others models and iPhones; Shall we forbiden the transmssion of these data ?

**Comment by ghisd** [comment]
accuracy is in meters (iOs and Android)

**Comment by TomDemulierChevret** [comment]
Fixed by #75
