### ISSUE TITLE
Delete history

### ISSUE THREAD

**Issue by ghisd** [openradiation/openradiation-mobile#63]
In history screen, add a generic "trash" button with this message

"Are you sure you wish to delete all the measurements ? By deleting your measurements, you clean your entire history but you do not delete the published data from the OpenRadiation base"

(in french : 
"Êtes-vous sûr de vouloir supprimer toutes les mesures ? En supprimant vos mesures, vous nettoyez tout votre historique mais vous ne supprimez pas les données déjà publiées de la base OpenRadiation")

If yes, all the measurements  with metadata locally stored are deleted and screen is refreshed

**Comment by TomDemulierChevret** [comment]
Fixed by https://github.com/openradiation/openradiation-mobile/commit/2c073c901dc981d6f7594c9f87c8c7c5fe395002.
